services:
  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd:/fluentd/etc:ro
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - demo-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: "host.docker.internal:24224"
        tag: "nginx.logs"
        fluentd-async: "true"
    networks:
      - demo-net

networks:
  demo-net:
